###################################
# EVALUACIONES
###################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluations
  labels:
    app: evaluations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluations
  template:
    metadata:
      labels:
        app: evaluations
    spec:
      containers:
        - name: evaluations
          image: us-central1-docker.pkg.dev/proyecto-final-miso-399322/proyecto-final-ms/evaluations:1.0
          ports:
            - containerPort: 5000
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: profinalsecrets 
                  key: uri
          imagePullPolicy: Always
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: proyecto-final-evaluations-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /evaluations/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-evaluations
  annotations:
    cloud.google.com/backend-config: '{"default": "proyecto-final-evaluations-config"}'
spec:
  type: NodePort
  selector:
    app: evaluations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31020
---