apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: proyecto-final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proyecto-final
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70