###################################
# MEDIADOR
###################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator
  labels:
    app: mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator
  template:
    metadata:
      labels:
        app: mediator
    spec:
      containers:
        - name: mediator
          image: us-central1-docker.pkg.dev/proyecto-final-miso-399322/proyecto-final-ms/mediator:1.0
          ports:
            - containerPort: 5000
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: profinalsecrets 
                  key: uri
            - name: USERS_PATH
              value: http://servicio-users
          imagePullPolicy: Always
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: proyecto-final-mediator-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /mediator/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-mediator
  annotations:
    cloud.google.com/backend-config: '{"default": "proyecto-final-mediator-config"}'
spec:
  type: NodePort
  selector:
    app: mediator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31016
---